# Generated by Django 3.0.3 on 2020-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('text', models.TextField()),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('due', models.DateTimeField(blank=True, verbose_name='date due')),
            ],
        ),
    ]
