# Generated by Django 3.0.3 on 2020-06-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200615_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
