# Generated by Django 3.0.3 on 2020-06-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200616_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True, verbose_name='list name')),
                ('slug', models.SlugField(max_length=63, unique=True, verbose_name='slug for list')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='list created time')),
            ],
        ),
    ]
